; For Unit MiniBPS (U090-B)

[env:------------------------------------------separator_bps_0]

; ================================
; UnitMiniBPS11 (QMP6988)
; ================================
; --------------------------------
; Examples
; --------------------------------
[env:UnitMiniBPS11_PlotToSerial_Core_Arduino_latest]
extends=Core, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/>
  +<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/>
  -<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/build/>
  -<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/managed_components/>

[env:UnitMiniBPS11_PlotToSerial_Core2_Arduino_latest]
extends=Core2, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/>
  +<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/>
  -<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/build/>
  -<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/managed_components/>

[env:UnitMiniBPS11_PlotToSerial_CoreS3_Arduino_latest]
extends=CoreS3, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/>
  +<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/>
  -<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/build/>
  -<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/managed_components/>

[env:UnitMiniBPS11_PlotToSerial_StampS3_Arduino_latest]
extends=StampS3, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/>
  +<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/>
  -<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/build/>
  -<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/managed_components/>

[env:UnitMiniBPS11_PlotToSerial_Atom_Arduino_latest]
extends=Atom, option_release, arduino_latest
build_flags = ${option_release.build_flags}
  -DARDUINO_USB_CDC_ON_BOOT=0
build_src_filter = +<*> -<.git/> -<.svn/>
  +<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/>
  -<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/build/>
  -<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/managed_components/>

[env:UnitMiniBPS11_PlotToSerial_AtomS3_Arduino_latest]
extends=AtomS3, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/>
  +<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/>
  -<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/build/>
  -<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/managed_components/>

[env:UnitMiniBPS11_PlotToSerial_AtomS3R_Arduino_latest]
extends=AtomS3R, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/>
  +<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/>
  -<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/build/>
  -<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/managed_components/>

[env:UnitMiniBPS11_PlotToSerial_Dial_Arduino_latest]
extends=Dial, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/>
  +<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/>
  -<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/build/>
  -<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/managed_components/>

[env:UnitMiniBPS11_PlotToSerial_NanoC6_Arduino_latest]
extends=NanoC6, option_release, pioarduino_latest
build_src_filter = +<*> -<.git/> -<.svn/>
  +<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/>
  -<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/build/>
  -<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/managed_components/>

[env:UnitMiniBPS11_PlotToSerial_NanoH2_Arduino_latest]
extends=NanoH2, option_release, pioarduino_latest
build_src_filter = +<*> -<.git/> -<.svn/>
  +<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/>
  -<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/build/>
  -<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/managed_components/>

[env:UnitMiniBPS11_PlotToSerial_StickCPlus_Arduino_latest]
extends=StickCPlus, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/>
  +<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/>
  -<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/build/>
  -<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/managed_components/>

[env:UnitMiniBPS11_PlotToSerial_StickCPlus2_Arduino_latest]
extends=StickCPlus2, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/>
  +<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/>
  -<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/build/>
  -<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/managed_components/>

[env:UnitMiniBPS11_PlotToSerial_StickS3_Arduino_latest]
extends=StickS3, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/>
  +<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/>
  -<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/build/>
  -<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/managed_components/>
build_flags = ${StickS3.build_flags}
  ${option_release.build_flags}

[env:UnitMiniBPS11_PlotToSerial_Paper_Arduino_latest]
extends=Paper, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/>
  +<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/>
  -<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/build/>
  -<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/managed_components/>

[env:UnitMiniBPS11_PlotToSerial_CoreInk_Arduino_latest]
extends=CoreInk, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/>
  +<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/>
  -<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/build/>
  -<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/managed_components/>

[env:UnitMiniBPS11_PlotToSerial_Fire_Arduino_latest]
extends=Fire, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/>
  +<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/>
  -<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/build/>
  -<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/managed_components/>

[env:UnitMiniBPS11_PlotToSerial_Cardputer_Arduino_latest]
extends=Cardputer, option_release, arduino_latest
build_flags = ${Cardputer.build_flags}
  ${option_release.build_flags}
build_src_filter = +<*> -<.git/> -<.svn/>
  +<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/>
  -<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/build/>
  -<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/managed_components/>

[env:UnitMiniBPS11_PlotToSerial_Tab5_Arduino_latest]
extends=Tab5, option_release, pioarduino_latest
build_flags = ${Tab5.build_flags}
  ${option_release.build_flags}
build_src_filter = +<*> -<.git/> -<.svn/>
  +<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/>
  -<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/build/>
  -<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/managed_components/>

[env:UnitMiniBPS11_PlotToSerial_NessoN1_Arduino_latest]
extends=NessoN1, option_release, pioarduino_latest
build_src_filter = +<*> -<.git/> -<.svn/>
  +<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/>
  -<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/build/>
  -<../examples/UnitUnified/UnitMiniBPS11/PlotToSerial/managed_components/>
